### PR TITLE
add public key and task to schema mapping

### PR DESCRIPTION
**Pull request by DwayneJengSage**
Testing done:
* ./gradlew check
* Manually tested HeartRate in simulator and verified that the data was being sent up with the correct schema revision.

Depends on https://github.com/Sage-Bionetworks/BridgeAndroidSDK/pull/59

### CODE REVIEW

**Comment by dephillipsmichael** [comment]
This repo is private? If so looks good to me and you are free to merge. Nice work on the schema identifier code.

**Comment by DwayneJengSage** [comment]
This repo is not private. What's the concern?

**Comment by dephillipsmichael** [comment]
I was under the impression that "pem" files need to be securely stored.  Sync with shannon or erin, IIRC they went through a bunch of hoops to make the "pem" file hidden in mPower but the rest of the project open source, so I imagine they had reasons.

**Comment by Erin-Mounts** [comment]
It’s not so much that they need to be securely stored; we’re not going to prevent people digging them out of the released apps from the app store. It’s more that we don’t want the default build of a public repo to point at a real study, so we have a separate private repo to put the .pem file and config file overrides with the real study name, and then the public repo has dummy versions so it can build but won’t pollute a real study’s data pool when Jane or Joe Random Developer finds and builds our public repos to kick the tires.

**Comment by DwayneJengSage** [comment]
Okay, I can remove the key for now.

Do we have a JIRA to insert the public key back into the official build? The last thing we want is to accidentally ship a build with the wrong key.

**Pull request merged**
